---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-api-config
data:
  api.bind: ":8080"
  api.jwt_secret: "change_me_after_deploy"
  gameservers.external_ip: "127.0.0.1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - 
          name: game-api
          image: ghcr.io/devnull-twitch/game-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            -
              name: WEBSERVER_BIND
              valueFrom:
                configMapKeyRef:
                  name: game-api-config
                  key: api.bind
            -
              name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: game-api-config
                  key: api.jwt_secret
            -
              name: EXTERNAL_IP
              valueFrom:
                configMapKeyRef:
                  name: game-api-config
                  key: gameservers.external_ip
            -
              name: USE_K8S
              value: "1"
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: game-api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8080
      nodePort: 30001